### ISSUE TITLE
Miner cannot connect. Unlocker.go and util.go needs to be fixed(Authorization fails) and multiple issues

### ISSUE THREAD

**Issue by arokapil** [NotoriousPyro/open-metaverse-pool#1]
while authorizing unlocker.go still tries to validate against ethereum address pattern.
address pattern needs to be corrected in util.go.

**Comment by arokapil** [comment]
payout fails when we set the keep transaction fee to false:

**Comment by arokapil** [comment]
Unlocker fails while calling 
func (u *BlockUnlocker) getExtraRewardForTx(height uint64, reward *big.Int) (*big.Int, error) {
>>>  blockValue := big.NewInt(BlockTxs.Transactions[0].Outputs[0].Value)

returns array index out of bond.

had to put a check to check to move forward.
 if len(BlockTxs.Transactions) != 0 {
        if len (BlockTxs.Transactions[0].Outputs) != 0 {
           
            blockValue := big.NewInt(BlockTxs.Transactions[0].Outputs[0].Value)
           	return new(big.Int).Sub(blockValue, reward), nil
        }
    }

**Comment by NotoriousPyro** [comment]
Are you using v3 API?

This all works perfectly for Metaverse.farm so it's most likely environmental or configuration issues.

**Comment by NotoriousPyro** [comment]
Please also do not put multiple issues in one issue. One issue per problem. There is also no problem with the miner verification. This matches the Metaverse address pattern:
```
addressPattern = regexp.MustCompile("^M[A-Z0-9]{1}[0-9a-zA-Z]{32}$")
```
![image](https://user-images.githubusercontent.com/706132/46101087-f26f5980-c1c2-11e8-96bf-1a20c6b9de15.png)

**Comment by arokapil** [comment]
may be the test is passing.. which is fine, however in actual flow it was breaking.. let me send you the details

**Comment by NotoriousPyro** [comment]
I hope you would send me the details because by "actual flow it was breaking" is not technically relevant and that "test" is regex and it is correct to match the address pattern.

**Comment by NotoriousPyro** [comment]
Please create a separate issue for each problem. I will close this off. Please include relevant details such as OS, versions, and logs.

**Comment by arokapil** [comment]
yes you are right... my bad i was actually testing on testnet therefore had to comment make few changes... to get the working...

**Comment by NotoriousPyro** [comment]
Yes, this will not work with testnet as of yet.
